environment          = "Production"
location             = "East US"
resource_group_name  = "prod-rg"
vnet_name            = "prod-vnet"
address_space        = ["10.0.0.0/16"]
subnet_name          = "prod-subnet"
subnet_prefixes      = ["10.0.1.0/24"]
public_ip_name       = "prod-ip"
nic_name             = "prod-nic"
vm_name              = "prod-vm"
vm_size              = "Standard_B2ms"
admin_username       = "adminuser"
ssh_public_key_path  = "~/.ssh/id_rsa.pub"
