environment          = "Development"
location             = "East US"
resource_group_name  = "dev-rg"
vnet_name            = "dev-vnet"
address_space        = ["10.1.0.0/16"]
subnet_name          = "dev-subnet"
subnet_prefixes      = ["10.1.1.0/24"]
public_ip_name       = "dev-ip"
nic_name             = "dev-nic"
vm_name              = "dev-vm"
vm_size              = "Standard_B2ms"
admin_username       = "adminuser"
ssh_public_key_path  = "~/.ssh/id_rsa.pub"
